Schema Registry 5: Protobuf (#458)
* Refactor test_do_not_auto_register_schemas

* Add JSON Schema case to test_do_not_auto_register_schemas

* Rearrange imports in protobuf.py

* Remove obsolete black extend-exclude entry

* Rename and recompile Test Protobuf schema

This eliminates the annoying PytestCollectionWarning. It is named
`Root` to distinguish it from a nested schema that will
be introduced later.

Additionally instruct black to not correct *_pb2.py files.
Note: force-exclude is required, or else black run via pre-commit would
still check the file.

* Add Nested Protobuf schema

Also added generate.sh helper script if we ever need to regenerate
protobufs again.

* Create serialization test cases with Nested Protobuf schema

* Check exception text in test_schema_registry_serialize_error

* Rename exception_text parameter to match for consistency

* Pass `include` from `BaseSettings.as_dict` to `BaseSettings.model_dump`

Protobuf accepts more configuration attributes than Avro
and JSON Schema. This change ensures that class constructors
do not raise errors due to unrecognized parameters.

* Separate parsing and serialization steps in ProtobufSerializer

* Catch and handle TypeError from google.protobuf.json_format.ParseDict

Original error is not very helpful:
TypeError: 'Nested' object is not iterable

* Integrate Schema Registry with Protobuf

* Update quixstreams/utils/settings.py

---------

Co-authored-by: Daniil Gusev <daniil@quix.io>